### ISSUE TITLE
Can I get the synthesized dataset of inpainted images using all the sub-categories of the COCO dataset?

### ISSUE THREAD

**Issue by 111xumengze** [AKASH2907/Forgery-Classification-via-Domain-Adaptation#1]
I'm looking forward to your reply.

**Comment by AKASH2907** [comment]
I have shared it initially on drive. It requires a huge space. I had to remove it as I needed space for my future project. I would be happy to share. I can do one thing. I'll add codes for dataset generation in the semantic inpainting and for CMF I'm making a different repo.
